[package]
name = "leenfetch"
version = "0.1.2"
edition = "2021"
description = "Fast, minimal, customizable system info tool in Rust (Neofetch alternative)"
license = "MIT"
repository = "https://github.com/drunkleen/leenfetch"
readme = "README.md"
categories = ["command-line-utilities", "visualization", "os"]
keywords = ["neofetch", "system", "terminal", "info", "rustfetch"]
authors = ["DrunkLeen <snape@drunkleen.com>"]

[dependencies]
dirs = "6.0.0"
libc = "0.2.172"
rand = "0.9.1"
winapi = { version = "0.3.9", features = ["winreg", "winuser", "winerror", "winbase", "winnt"] }
