[workspace]
members = ["cargo:."]

[dist]
cargo-dist-version = "0.28.0"
ci = "github"
install-updater = false
install-path = "CARGO_HOME"

[[dist.targets]]
triple = "x86_64-unknown-linux-gnu"

[[dist.targets]]
triple = "x86_64-pc-windows-msvc"

[[dist.targets]]
triple = "x86_64-unknown-linux-musl"

[[dist.targets]]
triple = "x86_64-apple-darwin"

[[dist.targets]]
triple = "aarch64-unknown-linux-gnu"

[[dist.targets]]
triple = "aarch64-pc-windows-msvc"

[[dist.installers]]
format = "shell"

[[dist.installers]]
format = "powershell"

[[dist.installers]]
format = "archive"

[[dist.installers]]
format = "deb"

[[dist.installers]]
format = "rpm"
