name: Build and Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    env:
      CARGO_TERM_COLOR: always
      CARGO_INCREMENTAL: 0

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: |
            x86_64-pc-windows-gnu
            aarch64-unknown-linux-gnu

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libx11-dev libxrandr-dev zip rpm

      - name: Install packaging tools
        run: |
          cargo install cargo-deb
          cargo install cargo-rpm
          cargo install cross

      - name: Build for Linux x86_64
        run: |
          cargo build --release --target-dir target/linux
          mkdir -p dist
          cp target/linux/release/leenfetch dist/leenfetch
          tar -czvf dist/leenfetch-linux.tar.gz -C dist leenfetch
          rm dist/leenfetch

      - name: Create .deb package
        run: |
          cargo deb
          cp target/debian/*.deb dist/

      - name: Create .rpm package
        run: |
          cargo rpm build
          cp target/release/rpmbuild/RPMS/x86_64/*.rpm dist/

      - name: Build for Windows
        run: |
          cross build --release --target x86_64-pc-windows-gnu --target-dir target/windows
          cp target/windows/x86_64-pc-windows-gnu/release/leenfetch.exe dist/
          cd dist && zip leenfetch-win.zip leenfetch.exe && rm leenfetch.exe && cd ..

      - name: Build for ARM (aarch64)
        run: |
          cross build --release --target aarch64-unknown-linux-gnu --target-dir target/aarch64
          cp target/aarch64/aarch64-unknown-linux-gnu/release/leenfetch dist/leenfetch-arm64
          cd dist && tar -czvf leenfetch-arm64.tar.gz leenfetch-arm64 && rm leenfetch-arm64 && cd ..

      - name: Generate checksums
        run: |
          cd dist
          sha256sum * > SHA256SUMS.txt
          cd ..

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
